version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres-server
    ports:
      - "3000:3000"
    volumes:
      - .:/mindfullness
      - bundler_gems:/usr/local/bundle/
    env_file: .env
    environment:
      RAILS_ENV: development
  postgres-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "mindfullness_development"
volumes:
  bundler_gems: